### ISSUE TITLE
네이버 앱 오탐지 문제

### ISSUE THREAD

**Issue by XiNiHa** [hibiyasleep/hongchik#1]
분명 Firefox Developer Edition 61.0b14로 접속했는데 네이버 앱이라고 다운로드가 안 된다고 나타나며, 다운로드는 아주 잘 작동합니다.

**Comment by hibiyasleep** [comment]
https://github.com/hibiyasleep/hongchik/commit/0ffeb7046aed277cf03d1d8fbf3f26f30254bdaa 에서 고쳐졌을 것 같습니다 ㅠㅠ 늦게 확인해서 죄송합니다
